version: "3"

services:

  backend:
    build: ./Back-end
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
      args:
        app_env: production

    ports:
      - "3000:3000"